//
// Created by lc on 2022/3/1.
//

#ifndef CRENDERER_VOLUMELIGHTRENDERER_HPP
#define CRENDERER_VOLUMELIGHTRENDERER_HPP

class VolumeLightRendererr {
    
};

#endif //CRENDERER_VOLUMELIGHTRENDERER_HPP
